name: Zig

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and check
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - run: zig build --summary all
      - run: zig build test
      - run: zig build run -- iter/core.iter
      - run: zig build run -- iter/std.iter
      - run: zig build run -- iter/test.iter
