name: Zig

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and check
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build --summary all
      - run: zig build test
      - run: zig build run -- core/base.iter >&2
